In [96]:
import numpy as np
import torch

In [84]:
def make_q(values):
    q = []
    length = len(values)
    for i, val in enumerate(values):
        q.append([val if j == i+1 or j == i-1 else 0 for j in range(length)])
    q = np.array(q).T
    q[0, -1] = 0
    q[-1, 0] = 0
    return q

In [85]:
make_q([0.4, 0.7, 0.8])

array([[0. , 0.7, 0. ],
       [0.4, 0. , 0.8],
       [0. , 0.7, 0. ]])

In [92]:
p = [0.1, 0.9, 0.95, 0.2]

In [93]:
logp = np.log(p)
q = make_q(p)

In [94]:
q

array([[0.  , 0.9 , 0.  , 0.  ],
       [0.1 , 0.  , 0.95, 0.  ],
       [0.  , 0.9 , 0.  , 0.2 ],
       [0.  , 0.  , 0.95, 0.  ]])

In [95]:
-np.matmul(np.matmul(p, q), logp)

0.6661930416635793

In [101]:
torch.matmul(torch.tensor(p), torch.from_numpy(q).float())

tensor([0.0900, 0.9450, 1.0450, 0.1900])

In [102]:
np.matmul(p, q)

array([0.09 , 0.945, 1.045, 0.19 ])

In [105]:
a = torch.tensor([p])

In [119]:
a.unsqueeze(-1).repeat(1,1,4)

tensor([[[0.1000, 0.1000, 0.1000, 0.1000],
         [0.9000, 0.9000, 0.9000, 0.9000],
         [0.9500, 0.9500, 0.9500, 0.9500],
         [0.2000, 0.2000, 0.2000, 0.2000]]])

In [115]:
a.shape

torch.Size([1, 4])

In [116]:
a

tensor([[0.1000, 0.9000, 0.9500, 0.2000]])

In [127]:
s = list(a.size())

In [128]:
s.extend([4])

In [129]:
s

[1, 4, 4]

In [141]:
def make_q(values):
    final_shape = list(values.size())
    final_shape.extend([final_shape[-1]])

    q = torch.zeros(final_shape)
    for i_b, b in enumerate(values):
        # Batch:
        for i, val in enumerate(b):
            for j in range(values.shape[1]):
                if j == i + 1 or j == i -1:
                    q[i_b, i, j] = val
                else:
                    q[i_b, i, j] = 0
    q[0, -1] = 0.
    q[-1, 0] = 0.
    return q

In [159]:
def make_q(values):
    q = []
    length = values.shape[-1]
    for ib in range(values.shape[0]):
        qb = []
        for i, val in enumerate(values[ib]):
            qb.append([val if j == i+1 or j == i-1 else 0 for j in range(length)])
        q.append(np.array(qb).T)
    return torch.tensor(q)

In [165]:
p = torch.tensor([[0.1, 0.2, 0.3, 0.9], [0.8, 0.9, 1, 0.32]])

In [166]:
a = make_q(p)

In [167]:
a[0]

tensor([[0.0000, 0.2000, 0.0000, 0.0000],
        [0.1000, 0.0000, 0.3000, 0.0000],
        [0.0000, 0.2000, 0.0000, 0.9000],
        [0.0000, 0.0000, 0.3000, 0.0000]], dtype=torch.float64)

In [168]:
a[1]

tensor([[0.0000, 0.9000, 0.0000, 0.0000],
        [0.8000, 0.0000, 1.0000, 0.0000],
        [0.0000, 0.9000, 0.0000, 0.3200],
        [0.0000, 0.0000, 1.0000, 0.0000]], dtype=torch.float64)

In [169]:
p.shape

torch.Size([2, 4])

In [171]:
torch.matmul(p, a.float())

tensor([[[0.0200, 0.0800, 0.3300, 0.2700],
         [0.0900, 0.3600, 0.3660, 0.9000]],

        [[0.1600, 0.3600, 1.1000, 0.0960],
         [0.7200, 1.6200, 1.2200, 0.3200]]])

In [172]:
torch.matmul(p[0], a[0].float())

tensor([0.0200, 0.0800, 0.3300, 0.2700])

In [173]:
p

tensor([[0.1000, 0.2000, 0.3000, 0.9000],
        [0.8000, 0.9000, 1.0000, 0.3200]])

In [174]:
p[0]

tensor([0.1000, 0.2000, 0.3000, 0.9000])

In [179]:
torch.matmul(p.unsqueeze(1), a.float()).shape

torch.Size([2, 1, 4])

In [177]:
p.unsqueeze(1).shape

torch.Size([2, 1, 4])